LEXICON_EN: dict[str, str] = {'/start': 'Hello! I\'m <b>Neural Style Transfer Bot</b>.\nI can style the pictures you send me using neural networks.\n\nUse these commands to control me:',
                              '/help': 'This bot can stylize pictures using Neural Style Transfer.\n\nFirsly, you need to choose style that will be applied to your photo.\nThen you should upload your photo and get back the result of neural style transfer.',
                              'send': 'The style has been succesfully chosen. Please, send the photo!',
                              'select': 'Select',
                              '/begin': 'Please, select one of the following styles!',
                              'other_answer': 'Sorry, I don\'t understand this command. Please use /start command to see the list of available commands',
                              'processing': 'The photo is being processed... Please, wait!',
                              '/author': 'The author of this bot is <a href="https://t.me/icherniaev">Ilya Chernyaev</a>\n\n You can contact me here:\n<a href="https://github.com/icherniaev">GitHub</a>\n<a href="https://linkedin.com/in/icherniaev">LinkedIn</a>\n<a href="mailto:icherniaev@nes.ru">E-mail</a> ',
                              'forward': '>>',
                              'backward': '<<',
                              'add': 'To choose another style, please use /begin.\nTo process another photo in this style just upload one more photo.'}